export const APP_STARTED = 'APP_STARTED';

export const USER_AUTO_LOGIN_STARTED = 'USER_AUTO_LOGIN_STARTED';
export const USER_AUTO_LOGIN_COMPLETED = 'USER_AUTO_LOGIN_COMPLETED';
export const USER_AUTO_LOGIN_FAILED = 'USER_AUTO_LOGIN_FAILED';

export const PAGE_STATE_ACQUIRED = 'PAGE_STATE_ACQUIRED';
